// ADR-004: Fascitis plantar evidence base
// Version: 1.0.0
// CTO clinical review: APPROVED — Mauricio Sobarzo, 2026-05-04
// Sources reviewed full text: Morrissey 2021 (BMJ), Charles 2023 (Frontiers Immunology),
//   Yang 2024 (Frontiers Neurology), Rhim 2021 (Life/PMC)

import type { DiagnosisEvidence } from '../types';

const fascitisPlantarEvidence: DiagnosisEvidence = {
  diagnosisId: 'fascitis-plantar',
  diagnosisName: 'Fascitis Plantar',
  icdCode: 'M72.2',
  version: '1.0.0',
  lastReviewed: '2026-05-04',
  nextReviewDue: '2027-05-04',
  reviewedBy: 'Mauricio Sobarzo, PT — Nº Colegiado 9657 COFCV',
  interventions: [
    {
      id: 'fp-001',
      name: 'Estiramiento específico de fascia plantar',
      category: 'exercise_therapy',
      description: 'Estiramiento en carga de la fascia plantar y cadena posterior (gastrocnemio/sóleo). El estiramiento específico de fascia plantar es superior al estiramiento de gastrocnemio solo para reducción de dolor a corto plazo.',
      evidenceLevel: 'high',
      references: [
        {
          authors: 'Morrissey D, Cotchett M, et al.',
          year: 2021,
          title: 'Management of plantar heel pain: a best practice guide informed by a systematic review, expert clinical reasoning and patient values',
          source: 'open_access_journal',
          doi: '10.1136/bjsports-2019-101970',
          pedroScore: 8,
          grade: 'high',
          design: 'systematic_review',
          sampleSize: 4351,
          fullTextReviewed: true,
          abstractConsistentWithFullText: true,
        },
      ],
      requiredTechniques: [],
      requiredEquipment: [],
      contraindications: [],
      relativeContraindications: [],
      notes: 'SMD 1.21 (95% CI 0.78–1.63) para dolor primer paso a corto plazo. Parte del tratamiento core junto con taping y educación. Sin contraindicaciones absolutas.',
    },
    {
      id: 'fp-002',
      name: 'Ondas de choque extracorpóreas (ESWT)',
      category: 'electrotherapy',
      description: 'Terapia de ondas de choque extracorpóreas — focalizada (fESWT) o radial (rESWT). Indicada especialmente en casos crónicos (>3 meses). Efecto grande sostenido a corto, medio y largo plazo.',
      evidenceLevel: 'high',
      references: [
        {
          authors: 'Charles R, Fang L, Zhu R, Wang J',
          year: 2023,
          title: 'The effectiveness of shockwave therapy on patellar tendinopathy, Achilles tendinopathy, and plantar fasciitis: a systematic review and meta-analysis',
          source: 'open_access_journal',
          doi: '10.3389/fimmu.2023.1193835',
          grade: 'high',
          design: 'meta_analysis',
          sampleSize: 2800,
          fullTextReviewed: true,
          abstractConsistentWithFullText: true,
        },
        {
          authors: 'Morrissey D, Cotchett M, et al.',
          year: 2021,
          title: 'Management of plantar heel pain: a best practice guide informed by a systematic review, expert clinical reasoning and patient values',
          source: 'open_access_journal',
          doi: '10.1136/bjsports-2019-101970',
          pedroScore: 8,
          grade: 'high',
          design: 'systematic_review',
          sampleSize: 4351,
          fullTextReviewed: true,
          abstractConsistentWithFullText: true,
        },
      ],
      requiredTechniques: [],
      requiredEquipment: ['Equipo de ondas de choque (fESWT o rESWT)'],
      contraindications: ['Marcapasos', 'Embarazo', 'Neoplasia local', 'Trastornos de coagulación'],
      relativeContraindications: ['Anticoagulación activa — evaluar con médico'],
      notes: 'fESWT OR 1.89 corto plazo, SMD 1.31 medio, SMD 1.67 largo plazo. Requiere equipamiento especializado — verificar disponibilidad antes de proponer. Segunda línea si no mejora con tratamiento core.',
    },
    {
      id: 'fp-003',
      name: 'Taping / vendaje funcional',
      category: 'taping',
      description: 'Low-dye taping o kinesiotaping para descarga mecánica de la fascia plantar. Efectivo para reducción de dolor a corto plazo (<1 semana). Combinado con estiramiento puede ser superior al estiramiento solo.',
      evidenceLevel: 'moderate',
      references: [
        {
          authors: 'Morrissey D, Cotchett M, et al.',
          year: 2021,
          title: 'Management of plantar heel pain: a best practice guide informed by a systematic review, expert clinical reasoning and patient values',
          source: 'open_access_journal',
          doi: '10.1136/bjsports-2019-101970',
          pedroScore: 8,
          grade: 'moderate',
          design: 'systematic_review',
          sampleSize: 4351,
          fullTextReviewed: true,
          abstractConsistentWithFullText: true,
        },
      ],
      requiredTechniques: ['Kinesiotaping', 'Vendaje funcional'],
      requiredEquipment: ['Tape neuromuscular o rígido'],
      contraindications: ['Alergia al adhesivo'],
      relativeContraindications: [],
      notes: 'SMD 0.47 (95% CI 0.05–0.88). Parte del tratamiento core. Evidencia más sólida a corto plazo. Técnica de aplicación relevante — low-dye vs kinesiotaping tienen perfiles similares.',
    },
    {
      id: 'fp-004',
      name: 'Ortesis plantar a medida',
      category: 'orthosis',
      description: 'Ortesis plantar custom o prefabricada de calidad para soporte del arco y descarga del calcáneo. Efectiva a corto y medio plazo. Segunda línea si no mejora con tratamiento core.',
      evidenceLevel: 'moderate',
      references: [
        {
          authors: 'Morrissey D, Cotchett M, et al.',
          year: 2021,
          title: 'Management of plantar heel pain: a best practice guide informed by a systematic review, expert clinical reasoning and patient values',
          source: 'open_access_journal',
          doi: '10.1136/bjsports-2019-101970',
          pedroScore: 8,
          grade: 'moderate',
          design: 'systematic_review',
          sampleSize: 4351,
          fullTextReviewed: true,
          abstractConsistentWithFullText: true,
        },
      ],
      requiredTechniques: [],
      requiredEquipment: [],
      contraindications: [],
      relativeContraindications: [],
      notes: 'SMD 0.41 corto plazo, SMD 0.55 medio plazo. Derivación a podólogo u ortopeda para confección. El fisio evalúa adecuación de la ortesis existente. Si el paciente ya tiene ortesis, evaluar antes de recomendar nueva.',
    },
    {
      id: 'fp-005',
      name: 'Punción seca',
      category: 'dry_needling',
      description: 'Punción seca en puntos gatillo miofasciales de fascia plantar, gastrocnemio y sóleo. Efectiva en reducción de dolor y mejora funcional. Efecto time-dependent — mínimo 1 mes para ver beneficio funcional.',
      evidenceLevel: 'moderate',
      references: [
        {
          authors: 'Yang A, Lin R, Xia M, Su H, He Y',
          year: 2024,
          title: 'The effectiveness of dry needling for plantar fasciitis: a systematic review and meta-analysis',
          source: 'open_access_journal',
          doi: '10.3389/fneur.2024.1520585',
          pedroScore: 7,
          grade: 'moderate',
          design: 'meta_analysis',
          sampleSize: 781,
          fullTextReviewed: true,
          abstractConsistentWithFullText: true,
        },
      ],
      requiredTechniques: ['Dry Needling / IMS'],
      requiredEquipment: ['Agujas de punción seca'],
      contraindications: ['Anticoagulación activa', 'Trastorno hemorrágico', 'Infección local'],
      relativeContraindications: ['Antiagregantes (Adiro, AAS) — evaluar riesgo de hematoma', 'Alergia a metales'],
      notes: 'VAS/NPRS 95% CI (−2.12, −1.76) p<0.0001 vs tratamiento convencional solo. Efecto visible desde 1 mes. CRÍTICO: contraindicación relativa con antiagregantes — cruzar siempre con medicación del paciente. Efectos adversos reportados: dolor local y hematoma, autolimitados.',
    },
  ],
};

export default fascitisPlantarEvidence;
