version: '3.8'

services:
  # Frontend - AiDuxCare V.2
  frontend:
    build:
      context: .
      target: development
    ports:
      - "5173:5173"
      - "5174:5174"
      - "5175:5175"
      - "5176:5176"
      - "5177:5177"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
      - VITE_FIREBASE_EMULATOR=true
    depends_on:
      - firebase-emulator
    networks:
      - aiduxcare-network
    command: npm run dev -- --host 0.0.0.0

  # Firebase Emulator
  firebase-emulator:
    image: node:20-bullseye
    ports:
      - "8080:8080"  # Firestore
      - "4000:4000"  # Firebase UI
      - "9150:9150"  # Firestore UI
    volumes:
      - ./firebase.json:/app/firebase.json
      - ./firestore.rules:/app/firestore.rules
      - emulator-data:/app/emulator-data
    working_dir: /app
    environment:
      - FIRESTORE_EMULATOR_HOST=0.0.0.0:8080
      - FIREBASE_AUTH_EMULATOR_HOST=0.0.0.0:9099
    command: >
      sh -c "npm install -g firebase-tools &&
             firebase emulators:start --only firestore --import=emulator-data --export-on-exit=emulator-data"
    networks:
      - aiduxcare-network

  # Backend API (si tienes un backend separado)
  backend:
    image: node:20-bullseye
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FIRESTORE_EMULATOR_HOST=firebase-emulator:8080
    depends_on:
      - firebase-emulator
    networks:
      - aiduxcare-network
    command: npm start

  # Nginx para producción
  nginx:
    build:
      context: .
      target: production
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - aiduxcare-network
    profiles:
      - production

volumes:
  emulator-data:

networks:
  aiduxcare-network:
    driver: bridge 