#!/bin/bash

echo "📋 CHECKLIST DE TESTING V2"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1. PÁGINA CARGA SIN ERRORES"
echo "   [ ] Console sin errores rojos"
echo "   [ ] WorkflowAnalysisTab visible"
echo ""
echo "2. PROBAR CASO SIMPLE (Carlos - deportista)"
echo "   [ ] Pegar transcripción"
echo "   [ ] Click en 'Analizar con IA'"
echo "   [ ] Métricas aparecen arriba"
echo "   [ ] Validación muestra % completitud"
echo "   [ ] Items auto-seleccionados"
echo ""
echo "3. PROBAR CASO COMPLEJO (Patricia - ketamina)"
echo "   [ ] Red flags detectados"
echo "   [ ] Ketamina aparece como crítico"
echo "   [ ] Auto-selección incluye red flags"
echo "   [ ] Métricas muestran tiempo y costo"
echo ""
echo "4. VERIFICAR MÉTRICAS"
echo "   [ ] Tiempo de procesamiento < 5 seg"
echo "   [ ] Completitud > 70%"
echo "   [ ] Costo estimado visible"
echo "   [ ] Red flags count correcto"
echo ""
echo "5. VALIDACIÓN SCHEMA"
echo "   [ ] Sin errores críticos (rojos)"
echo "   [ ] Advertencias (amarillas) si aplican"
echo "   [ ] Barra de progreso funciona"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Si todo funciona, la implementación V2 está lista!"
echo "IP defendible: Orquestación + Schema + Validación + Métricas"
