import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  FileText, 
  Search, 
  Copy, 
  Eye, 
  Calendar,
  User,
  ChevronRight,
  Filter
} from 'lucide-react';
import PersistenceService, { SavedNote } from '@/services/PersistenceService';
import { useAuth } from '@/context/AuthContext';
import logger from '@/shared/utils/logger';
import { FeedbackWidget } from '@/components/feedback/FeedbackWidget';
import { useBackupRestoration } from '@/hooks/useBackupRestoration';

interface NoteWithPatient extends SavedNote {
  patientName?: string;
}

export default function DocumentsPage() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [notes, setNotes] = useState<NoteWithPatient[]>([]);
  const [filteredNotes, setFilteredNotes] = useState<NoteWithPatient[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedNote, setSelectedNote] = useState<NoteWithPatient | null>(null);
  const [showPreview, setShowPreview] = useState(false);
  const [copySuccess, setCopySuccess] = useState<string | null>(null);

  // ✅ SPRINT 2 P2: Automatic backup restoration
  const { status: backupStatus } = useBackupRestoration(true);

  useEffect(() => {
    if (user) {
      loadNotes();
    }
  }, [user]);

  // Reload notes after backup restoration
  useEffect(() => {
    if (backupStatus.restored > 0 && user) {
      // Small delay to ensure Firestore has updated
      setTimeout(() => {
        loadNotes();
      }, 1000);
    }
  }, [backupStatus.restored, user]);

  useEffect(() => {
    filterNotes();
  }, [searchQuery, notes]);

  const loadNotes = async () => {
    try {
      setLoading(true);
      const allNotes = await PersistenceService.getAllNotes();
      // Sort by date (newest first)
      const sortedNotes = allNotes.sort((a, b) => 
        new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
      );
      setNotes(sortedNotes as NoteWithPatient[]);
    } catch (error) {
      logger.error('Error loading notes:', error);
    } finally {
      setLoading(false);
    }
  };

  const filterNotes = () => {
    if (!searchQuery.trim()) {
      setFilteredNotes(notes);
      return;
    }

    const query = searchQuery.toLowerCase();
    const filtered = notes.filter(note => 
      note.patientId.toLowerCase().includes(query) ||
      note.soapData.subjective.toLowerCase().includes(query) ||
      note.soapData.objective.toLowerCase().includes(query) ||
      note.soapData.assessment.toLowerCase().includes(query) ||
      note.soapData.plan.toLowerCase().includes(query) ||
      (note.patientName && note.patientName.toLowerCase().includes(query))
    );
    setFilteredNotes(filtered);
  };

  const formatSOAPNote = (note: SavedNote): string => {
    return `SOAP Note - ${new Date(note.createdAt).toLocaleDateString()}

PATIENT ID: ${note.patientId}
SESSION ID: ${note.sessionId}
DATE: ${new Date(note.createdAt).toLocaleString()}

SUBJECTIVE:
${note.soapData.subjective}

OBJECTIVE:
${note.soapData.objective}

ASSESSMENT:
${note.soapData.assessment}

PLAN:
${note.soapData.plan}

---
Generated by AiduxCare
Confidence: ${(note.soapData.confidence * 100).toFixed(1)}%
`;
  };

  const handleCopyToClipboard = async (note: SavedNote) => {
    try {
      const formattedNote = formatSOAPNote(note);
      await navigator.clipboard.writeText(formattedNote);
      setCopySuccess(note.id);
      setTimeout(() => setCopySuccess(null), 2000);
      logger.info('Note copied to clipboard:', note.id);
    } catch (error) {
      logger.error('Error copying to clipboard:', error);
      alert('Failed to copy note. Please try again.');
    }
  };

  const handlePreview = (note: NoteWithPatient) => {
    setSelectedNote(note);
    setShowPreview(true);
  };

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-CA', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-primary-ultralight to-white flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-blue mx-auto"></div>
          <p className="mt-4 text-gray-600 font-apple">Loading documents...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-ultralight to-white">
      {/* Header */}
      <div className="bg-white shadow-sm border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl sm:text-4xl font-light font-apple text-gray-900">
                Clinical Vault
              </h1>
              <p className="mt-2 text-gray-600 font-apple text-[15px]">
                Access and manage your SOAP notes
              </p>
            </div>
            <button
              onClick={() => navigate('/command-center')}
              className="px-4 py-2 text-primary-blue hover:text-primary-purple font-apple text-[15px] font-medium"
            >
              ← Back to Command Center
            </button>
          </div>
        </div>
      </div>

      {/* Search Bar */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
          <input
            type="text"
            placeholder="Search by patient ID, content..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-blue focus:border-transparent font-apple text-[15px]"
          />
        </div>
      </div>

      {/* Notes List */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-12">
        {filteredNotes.length === 0 ? (
          <div className="bg-white rounded-lg shadow-sm p-12 text-center">
            <FileText className="w-16 h-16 text-gray-300 mx-auto mb-4" />
            <h3 className="text-xl font-medium text-gray-900 mb-2 font-apple">
              {searchQuery ? 'No notes found' : 'No notes yet'}
            </h3>
            <p className="text-gray-500 font-apple text-[15px]">
              {searchQuery 
                ? 'Try adjusting your search query'
                : 'Start creating SOAP notes in the workflow to see them here'}
            </p>
          </div>
        ) : (
          <div className="grid gap-4">
            {filteredNotes.map((note) => (
              <div
                key={note.id}
                className="bg-white rounded-lg shadow-sm border border-gray-200 hover:shadow-md transition-shadow"
              >
                <div className="p-6">
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <div className="flex items-center gap-3 mb-2">
                        <FileText className="w-5 h-5 text-primary-blue" />
                        <h3 className="text-lg font-medium text-gray-900 font-apple">
                          Patient: {note.patientId}
                        </h3>
                        <span className="text-xs text-gray-500 font-apple">
                          {formatDate(note.createdAt)}
                        </span>
                      </div>
                      <div className="mt-2 text-sm text-gray-600 font-apple">
                        <p className="line-clamp-2">
                          <span className="font-medium">S:</span> {note.soapData.subjective.substring(0, 100)}...
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center gap-2 ml-4">
                      <button
                        onClick={() => handlePreview(note)}
                        className="p-3 min-w-[44px] min-h-[44px] text-gray-600 hover:text-primary-blue hover:bg-primary-ultralight rounded-lg transition-colors flex items-center justify-center"
                        title="Preview"
                      >
                        <Eye className="w-5 h-5" />
                      </button>
                      <button
                        onClick={() => handleCopyToClipboard(note)}
                        className={`p-3 min-w-[44px] min-h-[44px] rounded-lg transition-colors flex items-center justify-center ${
                          copySuccess === note.id
                            ? 'text-green-600 bg-green-50'
                            : 'text-gray-600 hover:text-primary-blue hover:bg-primary-ultralight'
                        }`}
                        title="Copy to clipboard"
                      >
                        <Copy className="w-5 h-5" />
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Preview Modal */}
      {showPreview && selectedNote && (
        <div className="fixed inset-0 bg-gray-900/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg shadow-xl max-w-4xl w-full max-h-[90vh] overflow-hidden flex flex-col">
            <div className="p-6 border-b border-gray-200 flex items-center justify-between">
              <div>
                <h2 className="text-2xl font-medium text-gray-900 font-apple">
                  SOAP Note Preview
                </h2>
                <p className="text-sm text-gray-500 mt-1 font-apple">
                  Patient: {selectedNote.patientId} • {formatDate(selectedNote.createdAt)}
                </p>
              </div>
              <button
                onClick={() => setShowPreview(false)}
                className="text-gray-400 hover:text-gray-600 min-w-[44px] min-h-[44px] flex items-center justify-center"
              >
                ✕
              </button>
            </div>
            <div className="p-6 overflow-y-auto flex-1">
              <div className="space-y-6 font-apple text-[15px]">
                <div>
                  <h3 className="text-lg font-medium text-primary-blue mb-2">SUBJECTIVE</h3>
                  <p className="text-gray-700 whitespace-pre-wrap">{selectedNote.soapData.subjective}</p>
                </div>
                <div>
                  <h3 className="text-lg font-medium text-primary-blue mb-2">OBJECTIVE</h3>
                  <p className="text-gray-700 whitespace-pre-wrap">{selectedNote.soapData.objective}</p>
                </div>
                <div>
                  <h3 className="text-lg font-medium text-primary-blue mb-2">ASSESSMENT</h3>
                  <p className="text-gray-700 whitespace-pre-wrap">{selectedNote.soapData.assessment}</p>
                </div>
                <div>
                  <h3 className="text-lg font-medium text-primary-blue mb-2">PLAN</h3>
                  <p className="text-gray-700 whitespace-pre-wrap">{selectedNote.soapData.plan}</p>
                </div>
              </div>
            </div>
            <div className="p-6 border-t border-gray-200 flex items-center justify-end gap-3">
              <button
                onClick={() => setShowPreview(false)}
                className="px-5 py-3 min-h-[48px] text-gray-700 hover:bg-gray-100 rounded-lg font-apple text-[15px] font-medium"
              >
                Close
              </button>
              <button
                onClick={() => {
                  handleCopyToClipboard(selectedNote);
                  setShowPreview(false);
                }}
                className="px-5 py-3 min-h-[48px] bg-gradient-to-r from-primary-blue to-primary-purple text-white rounded-lg hover:from-primary-blue-hover hover:to-primary-purple-hover font-apple text-[15px] font-medium"
              >
                Copy to Clipboard
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Feedback Widget */}
      <FeedbackWidget />
    </div>
  );
}

