/**
 * Unit Test: Copy vs Download Consistency
 * 
 * Tests that Copy to Clipboard and Download .txt generate identical content.
 * 
 * ✅ P3.3: DoD - Tests: confirmación del text output identical
 */

import { describe, it, expect } from 'vitest';
import type { SOAPNote } from '../../../types/vertex-ai';

// Mock generatePlainTextFormat function (same as in SOAPEditor)
function generatePlainTextFormat(soapNote: SOAPNote): string {
  return `SOAP Note - ${new Date().toISOString().split('T')[0]}

${'='.repeat(60)}

S: SUBJECTIVE
${'─'.repeat(60)}
${soapNote.subjective || 'No subjective information recorded.'}

${'─'.repeat(60)}

O: OBJECTIVE
${'─'.repeat(60)}
${soapNote.objective || 'No objective findings recorded.'}

${'─'.repeat(60)}

A: ASSESSMENT
${'─'.repeat(60)}
${soapNote.assessment || 'No assessment recorded.'}

${'─'.repeat(60)}

P: PLAN
${'─'.repeat(60)}
${soapNote.plan || 'No treatment plan recorded.'}

${'─'.repeat(60)}

${soapNote.referrals ? `Referrals:\n${soapNote.referrals}\n\n${'─'.repeat(60)}\n` : ''}
${soapNote.precautions ? `Precautions:\n${soapNote.precautions}\n\n${'─'.repeat(60)}\n` : ''}
${soapNote.additionalNotes ? `Additional Notes:\n${soapNote.additionalNotes}\n\n${'─'.repeat(60)}\n` : ''}

Generated by AiDuxCare
Document ID: ${Date.now()}
Status: Finalized

${'='.repeat(60)}`;
}

describe('Copy vs Download Consistency', () => {
  const mockSOAPNote: SOAPNote = {
    subjective: 'Patient reports low back pain radiating to right leg.',
    objective: 'Lumbar: SLR positive at 45° bilaterally. Slump test negative.',
    assessment: 'Patterns consistent with lumbar radiculopathy.',
    plan: 'Manual therapy, exercise prescription, follow-up in 1 week.',
  };

  it('should generate identical content for Copy and Download', () => {
    // Simulate Copy to Clipboard
    const copyContent = generatePlainTextFormat(mockSOAPNote);
    
    // Simulate Download .txt
    const downloadContent = generatePlainTextFormat(mockSOAPNote);
    
    // Both should be identical
    expect(copyContent).toBe(downloadContent);
  });

  it('should handle SOAP notes with all sections', () => {
    const fullSOAPNote: SOAPNote = {
      subjective: 'Patient reports low back pain.',
      objective: 'SLR positive.',
      assessment: 'Lumbar radiculopathy.',
      plan: 'Treatment plan.',
      referrals: 'Refer to orthopedist.',
      precautions: 'Avoid heavy lifting.',
      additionalNotes: 'Patient education provided.',
    };
    
    const copyContent = generatePlainTextFormat(fullSOAPNote);
    const downloadContent = generatePlainTextFormat(fullSOAPNote);
    
    expect(copyContent).toBe(downloadContent);
    expect(copyContent).toContain('Referrals:');
    expect(copyContent).toContain('Precautions:');
    expect(copyContent).toContain('Additional Notes:');
  });

  it('should handle SOAP notes with empty sections', () => {
    const emptySOAPNote: SOAPNote = {
      subjective: '',
      objective: '',
      assessment: '',
      plan: '',
    };
    
    const copyContent = generatePlainTextFormat(emptySOAPNote);
    const downloadContent = generatePlainTextFormat(emptySOAPNote);
    
    expect(copyContent).toBe(downloadContent);
    expect(copyContent).toContain('No subjective information recorded.');
    expect(copyContent).toContain('No objective findings recorded.');
  });

  it('should generate same format regardless of source (Copy vs Download)', () => {
    const content1 = generatePlainTextFormat(mockSOAPNote);
    const content2 = generatePlainTextFormat(mockSOAPNote);
    
    // Content should be byte-for-byte identical
    expect(content1.length).toBe(content2.length);
    expect(content1).toBe(content2);
    
    // Verify structure is consistent
    expect(content1).toMatch(/^SOAP Note - \d{4}-\d{2}-\d{2}/);
    expect(content1).toContain('S: SUBJECTIVE');
    expect(content1).toContain('O: OBJECTIVE');
    expect(content1).toContain('A: ASSESSMENT');
    expect(content1).toContain('P: PLAN');
    expect(content1).toContain('Generated by AiDuxCare');
  });

  describe('Edge Cases', () => {
    it('should handle very long SOAP notes', () => {
      const longSOAPNote: SOAPNote = {
        subjective: 'A'.repeat(1000),
        objective: 'B'.repeat(1000),
        assessment: 'C'.repeat(1000),
        plan: 'D'.repeat(1000),
      };
      
      const copyContent = generatePlainTextFormat(longSOAPNote);
      const downloadContent = generatePlainTextFormat(longSOAPNote);
      
      expect(copyContent).toBe(downloadContent);
      expect(copyContent.length).toBeGreaterThan(4000);
    });

    it('should handle special characters consistently', () => {
      const specialSOAPNote: SOAPNote = {
        subjective: 'Patient reports pain: 8/10. Symptoms include: tingling, numbness.',
        objective: 'SLR: 45° (positive). Range: 0-60° flexion.',
        assessment: 'Patterns consistent with L4-L5 radiculopathy.',
        plan: 'Treatment: TENS, US, exercise. Follow-up: 1 week.',
      };
      
      const copyContent = generatePlainTextFormat(specialSOAPNote);
      const downloadContent = generatePlainTextFormat(specialSOAPNote);
      
      expect(copyContent).toBe(downloadContent);
      expect(copyContent).toContain(':');
      expect(copyContent).toContain('°');
      expect(copyContent).toContain('-');
    });
  });
});

