name: EN-CA & Canada Market Guard
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read live PR metadata
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          TITLE=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} -q .title)
          BODY=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} -q .body)
          {
            echo "TITLE<<__PR_TITLE__"
            printf "%s\n" "$TITLE"
            echo "__PR_TITLE__"
            echo "BODY<<__PR_BODY__"
            printf "%s\n" "$BODY"
            echo "__PR_BODY__"
          } >> "$GITHUB_ENV"

      - name: Check PR metadata (Market/Language)
        run: |
          set -euo pipefail
          echo "---- DEBUG TITLE ----"; printf "%s\n" "$TITLE"
          echo "---- DEBUG BODY (200 chars) ----"; printf "%s" "$BODY" | head -c 200; echo
          if ! printf '%s\n%s\n' "$TITLE" "$BODY" | grep -qiE 'market:[[:space:]]*CA'; then
            echo "::error::PR missing Market: CA"; exit 1
          fi
          if ! printf '%s\n%s\n' "$TITLE" "$BODY" | grep -qiE 'language:[[:space:]]*en-CA'; then
            echo "::error::PR missing Language: en-CA"; exit 1
          fi
          echo "OK"
