name: Preflight Firebase Keys (Dual)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  preflight-uat:
    runs-on: ubuntu-latest
    env:
      VITE_ENV_TARGET: UAT
      VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY_UAT }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - name: UAT preflight
        run: node scripts/identitytoolkit-smoke.cjs "$VITE_ENV_TARGET"

  preflight-prod:
    runs-on: ubuntu-latest
    needs: preflight-uat
    env:
      VITE_ENV_TARGET: PROD
      VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY_PROD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - name: PROD preflight
        run: node scripts/identitytoolkit-smoke.cjs "$VITE_ENV_TARGET"
