name: Protect Infra Files
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Block deletions of protected files
        run: |
          set -e
          BASE_SHA=$(jq -r .pull_request.base.sha "$GITHUB_EVENT_PATH")
          HEAD_SHA=$(jq -r .pull_request.head.sha "$GITHUB_EVENT_PATH")
          PROTECTED_PATHS="
          .firebaserc
          firestore.rules
          firestore.indexes.json
          vite.config.ts
          .github/workflows/
          scripts/check-no-soap-logs.sh
          "
          CHANGES=$(git diff --name-status $BASE_SHA $HEAD_SHA)
          echo "$CHANGES"
          while read -r status file; do
            if [ "$status" = "D" ]; then
              for p in $PROTECTED_PATHS; do
                if [[ "$file" == "$p" || "$file" == $p* ]]; then
                  echo "❌ Protected delete: $file"
                  exit 1
                fi
              done
            fi
          done <<< "$CHANGES"
          echo "✅ No protected deletions"
