name: qa-eval-run (fresh-id)

on:
  push:
    tags:
      - '*'
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Manual tag (optional)'
        required: false
        type: string
  workflow_call:
    inputs:
      tag:
        description: 'Tag when called as reusable (optional)'
        required: false
        type: string

jobs:
  eval-on-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TAG_NAME: ${{ inputs.tag || (github.event_name == 'release' && github.event.release.tag_name) || (startsWith(github.ref, 'refs/tags/') && github.ref_name) || '' }}
    steps:
      - name: Debug context
        run: |
          echo "event=$GITHUB_EVENT_NAME"
          echo "ref=$GITHUB_REF"
          echo "ref_name=$GITHUB_REF_NAME"
          echo "TAG_NAME=${{ env.TAG_NAME }}"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TAG_NAME != '' && env.TAG_NAME || github.sha }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run QA eval
        run: npm run eval
      - name: Tag current eval report with QA gate tag
        if: always()
        run: |
          set -euo pipefail
          GATE_TAG="qa-eval-gate-$(date -u +%Y%m%dT%H%M%SZ)"
          echo "GATE_TAG=$GATE_TAG" >> $GITHUB_ENV
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$GATE_TAG" -m "QA Eval Gate for ${{ env.TAG_NAME || github.sha }}"
          git push origin "$GATE_TAG"
      - name: Update trendline
        if: always()
        run: npm run eval:report -- trendline
      - name: Commit trendline to main
        if: always()
        run: |
          set -euo pipefail
          git fetch origin main
          git checkout -B main origin/main
          test -f tools/eval/trends/quality-trend.md || exit 0
          git add tools/eval/trends/quality-trend.md
          git diff --cached --quiet || git commit -m "chore(eval): update quality trendline" \
            -m "" \
            -m "Market: CA" \
            -m "Language: en-CA" \
            -m "COMPLIANCE_CHECKED" \
            -m "Signed-off-by: ROADMAP_READ"
          git push origin main
      - name: Upload assets to Release
        if: always()
        uses: softprops/action-gh-release@v2
        with:
          files: |
            tools/eval/reports/*__*.jsonl
            tools/eval/reports/*__*.report.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
