name: release-assets-trend-v3 (disabled)
on:
  workflow_dispatch: {}   # manual only

jobs:
  disabled:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Disabled until lock/workflow is fixed."
