name: release-assets-and-trend

on:
  push:
    tags:
      - '*'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  eval-on-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      # Tag robusto para ambos eventos (push tag / release published / manual)
      TAG_NAME: ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref_name }}
    steps:
      - name: Checkout code (tag if available)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref_name }}

      - name: Debug context
        run: |
          echo "event=$GITHUB_EVENT_NAME"
          echo "ref=$GITHUB_REF"
          echo "ref_name=$GITHUB_REF_NAME"
          echo "tag(env.TAG_NAME)=${TAG_NAME}"
          git rev-parse --short=8 HEAD || true

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Run eval and report
        run: |
          set -euo pipefail
          mkdir -p tools/eval/reports
          npm run eval:run
          LATEST="$(ls -1t tools/eval/reports/*.jsonl | head -n1)"
          TS="$(date -u +%Y%m%dT%H%M%SZ)"
          TAG="${TAG_NAME:-$(git describe --tags --abbrev=0 || echo unknown)}"
          JSON_OUT="tools/eval/reports/${TAG}__${TS}.jsonl"
          cp -f "$LATEST" "$JSON_OUT"
          node tools/eval/reporter-md.cjs "$JSON_OUT" > "tools/eval/reports/${TAG}__${TS}.report.md"
          npm run eval:gate

      - name: Update trendline (workspace)
        run: npm run eval:trend:update

      - name: Commit trendline to main (if changed)
        run: |
          set -euo pipefail
          git fetch origin main
          # asegura commit en main
          git checkout -B main origin/main
          # mueve el archivo generado desde el checkout previo si hizo falta
          test -f tools/eval/trends/quality-trend.md || exit 0
          git add tools/eval/trends/quality-trend.md
          git diff --cached --quiet || git commit -m "chore(eval): update quality trendline

Market: CA
Language: en-CA
COMPLIANCE_CHECKED
Signed-off-by: ROADMAP_READ"
          git push origin main

      - name: Upload assets to Release
        if: always()
        uses: softprops/action-gh-release@v2
        with:
          files: |
            tools/eval/reports/${{ env.TAG_NAME }}__*.jsonl
            tools/eval/reports/${{ env.TAG_NAME }}__*.report.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
