name: security-docs-ci
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ripgrep
        run: sudo apt-get update && sudo apt-get install -y ripgrep

      - name: Make docs-sec
        run: |
          chmod +x scripts/security_doc_extractor.sh scripts/security_doc_extractor_supabase.sh
          make docs-sec

      - name: Ensure section is committed (no drift)
        run: |
          git add -N docs/architecture/section4_security_documented.md
          if ! git diff --exit-code -- docs/architecture/section4_security_documented.md; then
            echo "::error file=docs/architecture/section4_security_documented.md::El documento no está sincronizado. Ejecuta 'make docs-sec' y commitea el resultado."
            exit 1
          fi

      - name: Warn on permissive emulator rules
        run: |
          if [ -f firestore.rules ]; then
            if rg -n "allow read, write: if true;" firestore.rules; then
              echo "::warning ::Se detectó 'allow read, write: if true;' en firestore.rules (ok para emulador, revisar que no aplique a prod)."
            fi
          fi
